version: '3.4'

services:
  stbproxy:
    image: stb-proxy
    build:
      context: .
      dockerfile: ./Dockerfile
      target: release
    environment:
        - TZ=Europe/Berlin
        #- HOST=[MY_HOSTNAME]:8001 # Uncomment and set this to forward to a specific host name (optional)
    volumes:
        - ./config:/config
    ports:
        - 8001:8001   #publish port for stb-proxy container
    restart: unless-stopped